strict: true
docs_dir: ./docs
site_dir: ./site
site_name: mkdocs-jupyter-search

theme:
  name: material # mkdocs # readthedocs
  features:
    - search.suggest
    - search.highlight

plugins:
  - search
  - mkdocs-jupyter:
      include: ["index.ipynb"]
      ignore: []
      ignore_h1_titles: False
      include_source: True
      execute: True
      allow_errors: False
      kernel_name: .venv

nav:
  - index.ipynb
